
package client.NDL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NDLService", targetNamespace = "http://ndlservice", wsdlLocation = "http://localhost:1050/delservice?wsdl")
public class NDLService
    extends Service
{

    private final static URL NDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NDLSERVICE_EXCEPTION;
    private final static QName NDLSERVICE_QNAME = new QName("http://ndlservice", "NDLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1050/delservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NDLSERVICE_WSDL_LOCATION = url;
        NDLSERVICE_EXCEPTION = e;
    }

    public NDLService() {
        super(__getWsdlLocation(), NDLSERVICE_QNAME);
    }

    public NDLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NDLSERVICE_QNAME, features);
    }

    public NDLService(URL wsdlLocation) {
        super(wsdlLocation, NDLSERVICE_QNAME);
    }

    public NDLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NDLSERVICE_QNAME, features);
    }

    public NDLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NDLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightServerInterface
     */
    @WebEndpoint(name = "NDLServerPort")
    public FlightServerInterface getNDLServerPort() {
        return super.getPort(new QName("http://ndlservice", "NDLServerPort"), FlightServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightServerInterface
     */
    @WebEndpoint(name = "NDLServerPort")
    public FlightServerInterface getNDLServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ndlservice", "NDLServerPort"), FlightServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NDLSERVICE_EXCEPTION!= null) {
            throw NDLSERVICE_EXCEPTION;
        }
        return NDLSERVICE_WSDL_LOCATION;
    }

}
