
package client.MTL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTLService", targetNamespace = "http://mtlservice", wsdlLocation = "http://localhost:1050/mtlservice?wsdl")
public class MTLService
    extends Service
{

    private final static URL MTLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTLSERVICE_EXCEPTION;
    private final static QName MTLSERVICE_QNAME = new QName("http://mtlservice", "MTLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1050/mtlservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MTLSERVICE_WSDL_LOCATION = url;
        MTLSERVICE_EXCEPTION = e;
    }

    public MTLService() {
        super(__getWsdlLocation(), MTLSERVICE_QNAME);
    }

    public MTLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTLSERVICE_QNAME, features);
    }

    public MTLService(URL wsdlLocation) {
        super(wsdlLocation, MTLSERVICE_QNAME);
    }

    public MTLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTLSERVICE_QNAME, features);
    }

    public MTLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightServerInterface
     */
    @WebEndpoint(name = "MTLServerPort")
    public FlightServerInterface getMTLServerPort() {
        return super.getPort(new QName("http://mtlservice", "MTLServerPort"), FlightServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightServerInterface
     */
    @WebEndpoint(name = "MTLServerPort")
    public FlightServerInterface getMTLServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtlservice", "MTLServerPort"), FlightServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTLSERVICE_EXCEPTION!= null) {
            throw MTLSERVICE_EXCEPTION;
        }
        return MTLSERVICE_WSDL_LOCATION;
    }

}
