
package client.WDC;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WDCService", targetNamespace = "http://wdcservice", wsdlLocation = "http://localhost:1050/wstservice?wsdl")
public class WDCService
    extends Service
{

    private final static URL WDCSERVICE_WSDL_LOCATION;
    private final static WebServiceException WDCSERVICE_EXCEPTION;
    private final static QName WDCSERVICE_QNAME = new QName("http://wdcservice", "WDCService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1050/wstservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WDCSERVICE_WSDL_LOCATION = url;
        WDCSERVICE_EXCEPTION = e;
    }

    public WDCService() {
        super(__getWsdlLocation(), WDCSERVICE_QNAME);
    }

    public WDCService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WDCSERVICE_QNAME, features);
    }

    public WDCService(URL wsdlLocation) {
        super(wsdlLocation, WDCSERVICE_QNAME);
    }

    public WDCService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WDCSERVICE_QNAME, features);
    }

    public WDCService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WDCService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightServerInterface
     */
    @WebEndpoint(name = "WDCServerPort")
    public FlightServerInterface getWDCServerPort() {
        return super.getPort(new QName("http://wdcservice", "WDCServerPort"), FlightServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightServerInterface
     */
    @WebEndpoint(name = "WDCServerPort")
    public FlightServerInterface getWDCServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wdcservice", "WDCServerPort"), FlightServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WDCSERVICE_EXCEPTION!= null) {
            throw WDCSERVICE_EXCEPTION;
        }
        return WDCSERVICE_WSDL_LOCATION;
    }

}
